'''
boing: Boing is a utility for putting data generated by a HonSSH honeypot into an Elasticsearch database.

Note that "python setup.py test" invokes pytest on the package. With appropriately
configured setup.cfg, this will check both xxx_test modules and docstrings.

Copyright 2015, Tony Rein.
Licensed under MIT.
'''
import sys
from setuptools import setup, find_packages
from setuptools.command.test import test as TestCommand
from setuptools.command.install import install as _install
from pkg_resources import resource_stream
import shutil



# This is a plug-in for setuptools that will invoke py.test
# when you run python setup.py test
class PyTest(TestCommand):
    def finalize_options(self):
        TestCommand.finalize_options(self)
        self.test_args = []
        self.test_suite = True

    def run_tests(self):
        import pytest  # import here, because outside the required eggs aren't loaded yet
        sys.exit(pytest.main(self.test_args))


version = "0.9.1b"

    



class install(_install):
    def install_config_file(self):
        instream = resource_stream('boing', '/data/boing.cfg')
        outfilename = '/etc/boing.cfg'
        with open(outfilename, 'wt') as f:
            shutil.copyfileobj(instream, f)

    def run(self):
        _install.run(self)
        print 'Post-install stage...'
        print 'Copying config file...'
        self.install_config_file()

setup(name="boing",
      version=version,
      description="Boing is a utility for putting data generated by a HonSSH honeypot into an Elasticsearch database.",
      long_description=open("README.rst").read(),
      classifiers=[ # Get strings from http://pypi.python.org/pypi?%3Aaction=list_classifiers
        'Development Status :: 1 - Planning',
        'Programming Language :: Python'
      ],
      keywords="HonSSH Elasticsearch Python Honeypot cybersecurity", # Separate with spaces
      author="Tony Rein",
      author_email="boing.to.elasticsearch@gmail.com",
      url="https://github.com/tonyrein/boing.git",
      license="MIT",
      packages=find_packages(exclude=['examples', 'tests']),
      include_package_data=True,
      zip_safe=True,
      tests_require=['pytest'],
      cmdclass={'test': PyTest, 'install': install},
      package_data      = {'boing': ['data/boing_schema.sql', 'data/boing.cfg']},
      # TODO: List of packages that this one depends upon:   
      install_requires=['iso8601', 'tzlocal', 'GeoIP', 'elasticutils'],
      # TODO: List executable scripts, provided by the package (this is just an example)
      entry_points={
        'console_scripts': 
            ['boing=boing.main:main']
      }
)
